version: '3.9'
services:

  webservice:
    init: true
    build:
     context: ./WebService
    restart: always
    ports: 
     - 8080:8080
    env_file:
     - ./WebService/.env.sample

  # Add other microservices over here

