name: Deploying to development...
on:
  push:
    branches:
      - dev
    workflow_run:
      workflows: ["Build Docker Image"]
      types: 
       -completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
     